### ISSUE TITLE
Incorrect result to "factorize" over integers when using only FLINT, not NTL

### ISSUE THREAD

**Issue by fingolfin** [Singular/Singular#1025] opened 2020-08-17 07:21 UTC
Using latest `spielwiese`, I get this:
```
> ring r = integer,(x,y,z,w),dp;
> poly f2 = 123*(57*y^3 + w^5)^3*(x^2 + x+1)^2*(x + y*z)^2;
> factorize(f2);
[1]:
   _[1]=1
   _[2]=x2+x+1
   _[3]=yz+x
   _[4]=w5+57y3
[2]:
   1,2,2,3
```

When building Singular with NTL instead of FLINT, I get the correct result:
```
> ring r = integer,(x,y,z,w),dp;
> poly f2 = 123*(57*y^3 + w^5)^3*(x^2 + x+1)^2*(x + y*z)^2;
> factorize(f2);
[1]:
   _[1]=123
   _[2]=x2+x+1
   _[3]=yz+x
   _[4]=w5+57y3
[2]:
   1,2,2,3
```

**Comment by tthsqe12** [comment] 2020-08-17 09:12
I am looking into this.

**Comment by hannes14** [comment] 2020-08-17 09:46
On Mon, Aug 17, 2020 at 02:13:06AM -0700, tthsqe12 wrote:
> I am looking into this.
Hint:
e   1. ring r=ZZ,(x,y,z,w),ds;
e   2> factorize (123*(57*y^3 + w^5)^3*(x^2 + x+1)^2*(x + y*z)^2);
[1]:
   _[1]=1
   _[2]=1+x+x2
   _[3]=x+yz
   _[4]=57y3+w5
[2]:
   1,2,2,3
e   3> ring r2=QQ,(x,y,z,w),ds;
e   4> factorize (123*(57*y^3 + w^5)^3*(x^2 + x+1)^2*(x + y*z)^2);
[1]:
   _[1]=123
   _[2]=1+x+x2
   _[3]=x+yz
   _[4]=57y3+w5
[2]:
   1,2,2,3
e   5> $
factorize over Z and Q uses the same routines in factory and flint,
so the bug must be in singclap_factorize in libpolys/polysclapsing.cc

**Comment by hannes14** [comment] 2020-08-17 14:36
fixed with https://github.com/Singular/Singular/commit/3d56a756d62a0ea4ee1f27e24ad9768a6657d730

**Comment by tthsqe12** [comment] 2020-08-17 14:53
I don't understand this fix. If this code was not needed before, why is it needed now?

**Comment by hannes14** [comment] 2020-08-17 16:43
On Mon, Aug 17, 2020 at 02:53:15PM +0000, tthsqe12 wrote:
Singular uses usually (traditionally) rings Q[...], and this fix adapt the handling
for polynomials in Q[...] also to polynomials in Z[...], which was
forgotten. (Z is a recent addition)

**Comment by fingolfin** [comment] 2020-08-18 08:12
Perhaps we should also add a test or two which exercises this feature, to make sure it does not regress? Or perhaps such a test already exists, and we simply didn't notice because the test suite still produces too many failures when using FLINT instead of NTL? (As seen on PR #1021)

**Comment by tthsqe12** [comment] 2020-08-18 12:08
I do not fully understand 3d56a75. Before this commit, the problem is in sqrFreeZ in fac_sqrtfree.cc.
Essentially, the input polynomial is the expanded form of 123*(57*y^3 + w^5)^3*(x^2 + x+1)^2*(x + y*z)^2.
Then, because SW_RATIONAL is on, sqrFreeZ outputs the incorrect factorization (57*y^3 + w^5)^3*(x^2 + x+1)^2*(x + y*z)^2. This mean that factory has lost the 123, so of course final answer is missing it.
Now, if I manually turn of SW_RATIONAL, factory get the correct factorization.
My point is that factory is calculating the wrong factorization, possibly because of SW_RATIONAL.
What is the meaning of SW_RATIONAL, and does 3d56a75 turn it off for factory in this case?

**Comment by fingolfin** [comment] 2020-09-18 12:13
@hannes14 could you perhaps explain? Thank you!

**Comment by hannes14** [comment] 2020-09-18 12:39
SW_RATIONAL changes between computations in QQ resp. ZZ (mainly mod, %)
All these INTERNAL routines have assumptions on the input (like sqrFreeZ: square free polynomial over ZZ, content removed),
so the fix changes the preprocessing in singclap_factorize (removing denominators, removing content: these extra (constant) factors are kept in NN and and the end added to the final result).
The rotines for that were already there (for coefficients in QQ, QQ(alpha)), but missed the case of coefficients in ZZ.

**Closed** 2020-11-26 01:24 UTC
